# Use forge 36 and later
modLoader="javafml"
loaderVersion="[36,)"

# This is standard one. Probably will change later
license="All rights reserved" # https://choosealicense.com/

issueTrackerURL="https://github.com/Capaldi12/projectex/issues"

[[mods]]
modId="projectex"
version="${file.jarVersion}"

displayName="ProjectEX"
displayURL="https://github.com/Capaldi12/projectex"
logoFile="logo.png"

credits="Port by Capaldi12 aka 4sentepoid4"
authors="LatvianModder"

description='''
This is port of Project EX by LatvianModder
I have not created any part of this mod, only adapted it to work with minecraft 1.16

Original mod curseforge page - https://www.curseforge.com/minecraft/mc-mods/project-ex
Original mod repository - https://github.com/LatvianModder/Project-EX

This mod is addon for ProjectE mod and requires it to work. You can get it here: https://www.curseforge.com/minecraft/mc-mods/projecte
'''

# Will leave it here for now
# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional

[[dependencies.projectex]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.projectex]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"

[[dependencies.projectex]]
    modId="projecte"
    mandatory=true
    versionRange="[PE1.0.1B,)"
    ordering="NONE"
    side="BOTH"
